table financials
	lineageTag: c7092923-54ed-42b4-a7d2-e61e9b9f3d01

	/// Sum of net sales
	measure 'Total Sales' = SUM(financials[Sales])
		formatString: #,##0
		lineageTag: 3031368b-90ab-4007-8db2-d2e6062b56ba

	/// Sum of profit
	measure 'Total Profit' = SUM(financials[Profit])
		formatString: #,##0
		lineageTag: c7b63476-2ecd-4b0b-ae1f-c4890bd64d5b

	/// Sum of units sold
	measure 'Total Units Sold' = SUM(financials[Units Sold])
		formatString: #,##0
		lineageTag: 649d6f5f-f6c7-4783-b6c2-135ef431aec5

	/// Sum of cost of goods sold
	measure 'Total COGS' = SUM(financials[COGS])
		formatString: #,##0
		lineageTag: 9a0326bf-995b-49fc-a5e4-9f9af24f0f4a

	/// Sum of gross sales
	measure 'Total Gross Sales' = SUM(financials[Gross Sales])
		formatString: #,##0
		lineageTag: 36cad2c6-c5ef-4da7-8f66-6780cbbbbce1

	/// Sum of discounts
	measure 'Total Discounts' = SUM(financials[Discounts])
		formatString: #,##0
		lineageTag: 91a2bb11-8f01-49df-a8dd-547f2d4de603

	/// Profit as a percentage of sales
	measure 'Profit Margin %' = DIVIDE(SUM(financials[Profit]), SUM(financials[Sales]))
		formatString: 0.0%
		lineageTag: e0bc40e1-ce25-4d96-ac7d-63ee241309c9

	/// Discounts as a percentage of gross sales
	measure 'Discount %' = DIVIDE(SUM(financials[Discounts]), SUM(financials[Gross Sales]))
		formatString: 0.0%
		lineageTag: 3d2d8cf8-81ff-417a-b784-e631fc470e66

	/// Average sale price per unit
	measure 'Avg Sale Price' = AVERAGE(financials[Sale Price])
		formatString: #,##0
		lineageTag: fd786915-44ab-4f59-b4aa-15cec561e8fc

	/// Average manufacturing price per unit
	measure 'Avg Manufacturing Price' = AVERAGE(financials[Manufacturing Price])
		formatString: #,##0
		lineageTag: 111e2bef-c2e7-4ef5-8e48-e6756e751f4f

	/// Total Profit divided by Total Units Sold
	measure 'Profit per Unit' = DIVIDE([Total Profit], [Total Units Sold])
		formatString: #,##0.00
		lineageTag: d8d2e923-ec9c-45cb-b77c-cb6335046553

	measure 'Transaction Count' = COUNTROWS(financials)
		formatString: #,0
		lineageTag: 33c8394f-7931-4148-a1cb-67dfab99b6d8

	measure 'Product Count' = DISTINCTCOUNT(financials[Product])
		formatString: #,0
		lineageTag: bf314c5c-339e-4c54-846c-7690e70ba68f

	column Segment
		dataType: string
		lineageTag: 070ab03e-8346-4eb3-95c8-0976123d0eed
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: c1284d35-934b-402e-a681-b8c637825495
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a957c33c-9d52-4367-b81a-c8d327266568
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: f5f8adf3-10b4-4e6e-b030-291e96008b07
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: eb0fe431-6b5b-4bd9-ab84-f8a5b6dc37f9
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 07916ebd-26ec-4e4d-ae59-9c748bc1a7b3
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: e16dc20c-0ca7-40b1-ad7d-9aae87585fa1
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 532a9894-e593-436d-afd1-547c076c7658
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: f079bf26-1116-4b22-b8c9-9e33bbd75b94
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 5b8e7c5c-9c46-4789-b5a4-10946578dd1e
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 7f0ec642-3aa4-444c-840a-e491635ab1f0
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 8e43b0db-a998-4fb5-826c-204a1992901e
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0b8353ba-f96c-4d6c-870c-f735494ef1b4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: b6c513a0-07b5-4431-a23f-a35b75bb75b1
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: cb7a8f7f-a3a6-4e32-b090-84b4a34b3ca3
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2fba9468-d62f-4975-88db-37f92ee96d30
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.152.1279.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

